openapi: 3.0.3
info:
  title: EMF Indexer
  version: 0.1.0
  description: EMF agent indexer OpenAPI specification.
servers:
  - url: http://127.0.0.1:9494
    description: Local environment
paths:
  /entities:
    get:
      summary: Query on-chain entities
      tags: ["General"]
      operationId: QueryEntities
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  account_id:
                    type: string
                  created_at:
                    type: integer
                required: [account_id, created_at]
        500:
          $ref: "#/components/responses/InternalServerError"
  /sub-entities:
    get:
      summary: Query on-chain sub-entities entities
      tags: ["General"]
      operationId: QuerySubEntities
      parameters:
        - $ref: "#/components/parameters/OptionalAccountId"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  entity:
                    type: string
                  account_id:
                    type: string
                  location:
                    type: string
                  created_at:
                    type: integer
                required: [entity, account_id, location, created_at]
        500:
          $ref: "#/components/responses/InternalServerError"
  /spikes:
    get:
      summary: Query on-chain spikes
      tags: ["General"]
      operationId: QuerySpikes
      parameters:
        - $ref: "#/components/parameters/RequiredAccountId"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  sub_entity:
                    type: string
                  value:
                    type: string
                  created_at:
                    type: integer
                required: [sub_entity, value, created_at]
        500:
          $ref: "#/components/responses/InternalServerError"
  /too-many-spikes:
    get:
      summary: Query on-chain too many spikes
      tags: ["General"]
      operationId: QueryTooManySpikes
      parameters:
        - $ref: "#/components/parameters/RequiredAccountId"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  sub_entity:
                    type: string
                  created_at:
                    type: integer
                required: [sub_entity, created_at]
        500:
          $ref: "#/components/responses/InternalServerError"
  /ready-certificates:
    get:
      summary: Query on-chain ready certificates
      tags: ["General"]
      operationId: QueryReadyCertificates
      parameters:
        - $ref: "#/components/parameters/RequiredAccountId"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  sub_entity:
                    type: string
                  created_at:
                    type: integer
                required: [sub_entity, created_at]
        500:
          $ref: "#/components/responses/InternalServerError"
  /issued-certificates:
    get:
      summary: Query on-chain issued certificates
      tags: ["General"]
      operationId: QueryIssuedCertificates
      parameters:
        - $ref: "#/components/parameters/RequiredAccountId"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  sub_entity:
                    type: string
                  c_index:
                    type: integer
                  created_at:
                    type: integer
                required: [sub_entity, c_index, created_at]
        500:
          $ref: "#/components/responses/InternalServerError"
components:
  responses:
    InternalServerError:
      description: Internal server error
      content:
        application/text:
          schema:
            type: string
  parameters:
    OptionalAccountId:
      in: query
      name: account_id
      schema:
        type: string
      required: false
    RequiredAccountId:
      in: query
      name: account_id
      schema:
        type: string
      required: true
