[package]
name = "agent"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread", "sync", "signal", "time"], default-features = false }
log = { version = "0.4.21", features = [], default-features = false }
env_logger = { version = "0.11.3", features = ["auto-color", "humantime"], default-features = false }

[dev-dependencies]
tokio = { version = "1.37.0", features = ["io-util", "sync", "time", "process"], default-features = false }
